// Category data structure for Ola Shop
export const categories = [
  {
    id: 'deals',
    nameAr: 'تسوق بأسعار أقل',
    nameEn: 'Shop at Lower Prices',
    icon: '🛍️',
    href: '/products?category=deals',
    subcategories: [
      { id: 'under-300', nameAr: 'أقل من 300 جنيه', nameEn: 'Under 300 EGP', href: '/products?price=under-300' },
      { id: 'under-500', nameAr: 'أقل من 500 جنيه', nameEn: 'Under 500 EGP', href: '/products?price=under-500' },
      { id: 'under-700', nameAr: 'أقل من 700 جنيه', nameEn: 'Under 700 EGP', href: '/products?price=under-700' },
      { id: 'under-1000', nameAr: 'أقل من 1000 جنيه', nameEn: 'Under 1000 EGP', href: '/products?price=under-1000' },
    ],
  },
  {
    id: 'makeup',
    nameAr: 'المكياج',
    nameEn: 'Makeup',
    icon: '💄',
    href: '/products?category=makeup',
    subcategories: [
      {
        id: 'face',
        nameAr: 'الوجه',
        nameEn: 'Face',
        items: [
          { nameAr: 'برايمر', nameEn: 'Primer', href: '/products?category=makeup&sub=primer' },
          { nameAr: 'جلو فاتر', nameEn: 'Glow Water', href: '/products?category=makeup&sub=glow-water' },
          { nameAr: 'بي بي و سي سي كريم', nameEn: 'BB & CC Cream', href: '/products?category=makeup&sub=bb-cc-cream' },
          { nameAr: 'كريم أساس', nameEn: 'Foundation', href: '/products?category=makeup&sub=foundation' },
          { nameAr: 'مصحح و كونسيلر', nameEn: 'Corrector & Concealer', href: '/products?category=makeup&sub=concealer' },
          { nameAr: 'بلاشر', nameEn: 'Blush', href: '/products?category=makeup&sub=blush' },
          { nameAr: 'بودر', nameEn: 'Powder', href: '/products?category=makeup&sub=powder' },
          { nameAr: 'كونتور', nameEn: 'Contour', href: '/products?category=makeup&sub=contour' },
          { nameAr: 'هايلايتر', nameEn: 'Highlighter', href: '/products?category=makeup&sub=highlighter' },
          { nameAr: 'كوشينات وقوس باودر', nameEn: 'Cushions & Puff Powder', href: '/products?category=makeup&sub=cushions' },
          { nameAr: 'باليت ومجموعات الوجه', nameEn: 'Palettes & Face Sets', href: '/products?category=makeup&sub=palettes' },
          { nameAr: 'إسبراي الثبيت', nameEn: 'Setting Spray', href: '/products?category=makeup&sub=setting-spray' },
        ],
      },
      {
        id: 'eyes',
        nameAr: 'العيون',
        nameEn: 'Eyes',
        items: [
          { nameAr: 'الحواجب', nameEn: 'Eyebrows', href: '/products?category=makeup&sub=eyebrows' },
          { nameAr: 'أشادو', nameEn: 'Shadow', href: '/products?category=makeup&sub=eyeshadow' },
          { nameAr: 'آيلينر', nameEn: 'Eyeliner', href: '/products?category=makeup&sub=eyeliner' },
          { nameAr: 'كحل كاجال', nameEn: 'Kajal', href: '/products?category=makeup&sub=kajal' },
          { nameAr: 'ماسكرا', nameEn: 'Mascara', href: '/products?category=makeup&sub=mascara' },
          { nameAr: 'الروموش والاكسسوارات', nameEn: 'Lashes & Accessories', href: '/products?category=makeup&sub=lashes' },
          { nameAr: 'العدسات اللاصقة', nameEn: 'Contact Lenses', href: '/products?category=makeup&sub=contacts' },
        ],
      },
      {
        id: 'lips',
        nameAr: 'الشفاه',
        nameEn: 'Lips',
        items: [
          { nameAr: 'أحمر شفاه', nameEn: 'Lipstick', href: '/products?category=makeup&sub=lipstick' },
          { nameAr: 'ملمع الشفاه', nameEn: 'Lip Gloss', href: '/products?category=makeup&sub=lip-gloss' },
          { nameAr: 'قلم تحديد الشفاه', nameEn: 'Lip Liner', href: '/products?category=makeup&sub=lip-liner' },
          { nameAr: 'مرطب الشفاه', nameEn: 'Lip Balm', href: '/products?category=makeup&sub=lip-balm' },
        ],
      },
      {
        id: 'tools',
        nameAr: 'أدوات المكياج',
        nameEn: 'Makeup Tools',
        items: [
          { nameAr: 'فرش المكياج', nameEn: 'Makeup Brushes', href: '/products?category=makeup&sub=brushes' },
          { nameAr: 'إسفنج المكياج', nameEn: 'Makeup Sponges', href: '/products?category=makeup&sub=sponges' },
          { nameAr: 'مزيل المكياج', nameEn: 'Makeup Remover', href: '/products?category=makeup&sub=remover' },
        ],
      },
    ],
  },
  {
    id: 'skincare',
    nameAr: 'العناية بالبشرة',
    nameEn: 'Skincare',
    icon: '🧴',
    href: '/products?category=skincare',
    subcategories: [
      { nameAr: 'منتجات تنظيف الوجه', nameEn: 'Face Cleansing', href: '/products?category=skincare&sub=cleansing' },
      { nameAr: 'مقشر الوجه', nameEn: 'Face Scrub', href: '/products?category=skincare&sub=scrub' },
      { nameAr: 'تونر', nameEn: 'Toner', href: '/products?category=skincare&sub=toner' },
      { nameAr: 'ماسك الوجه', nameEn: 'Face Mask', href: '/products?category=skincare&sub=mask' },
      { nameAr: 'سيروم الوجه', nameEn: 'Face Serum', href: '/products?category=skincare&sub=serum' },
      { nameAr: 'مرطب', nameEn: 'Moisturizer', href: '/products?category=skincare&sub=moisturizer' },
      { nameAr: 'واقي الشمس', nameEn: 'Sunscreen', href: '/products?category=skincare&sub=sunscreen' },
      { nameAr: 'مقاومة الشيخوخة', nameEn: 'Anti-aging', href: '/products?category=skincare&sub=anti-aging' },
      { nameAr: 'صابون الوجه والجسم', nameEn: 'Face & Body Soap', href: '/products?category=skincare&sub=soap' },
      { nameAr: 'مزيل المكياج', nameEn: 'Makeup Remover', href: '/products?category=skincare&sub=makeup-remover' },
      { nameAr: 'العناية بالعين', nameEn: 'Eye Care', href: '/products?category=skincare&sub=eye-care' },
      { nameAr: 'ماسك العين', nameEn: 'Eye Mask', href: '/products?category=skincare&sub=eye-mask' },
      { nameAr: 'العناية بالروموش', nameEn: 'Lash Care', href: '/products?category=skincare&sub=lash-care' },
      { nameAr: 'العناية بالشفاه', nameEn: 'Lip Care', href: '/products?category=skincare&sub=lip-care' },
      { nameAr: 'أدوات العناية بالبشرة', nameEn: 'Skincare Tools', href: '/products?category=skincare&sub=tools' },
    ],
  },
  {
    id: 'body-care',
    nameAr: 'العناية بالجسم',
    nameEn: 'Body Care',
    icon: '💆',
    href: '/products?category=body-care',
    subcategories: [
      { nameAr: 'كريم ولوشن', nameEn: 'Cream & Lotion', href: '/products?category=body-care&sub=lotion' },
      { nameAr: 'زبدة الجسم', nameEn: 'Body Butter', href: '/products?category=body-care&sub=butter' },
      { nameAr: 'سوفليه الجسم', nameEn: 'Body Soufflé', href: '/products?category=body-care&sub=souffle' },
      { nameAr: 'جل / زيوت الجسم', nameEn: 'Body Gel / Oils', href: '/products?category=body-care&sub=oils' },
      { nameAr: 'بادي ميست', nameEn: 'Body Mist', href: '/products?category=body-care&sub=mist' },
      { nameAr: 'بادي سبراي', nameEn: 'Body Spray', href: '/products?category=body-care&sub=spray' },
      { nameAr: 'بادي مسك', nameEn: 'Body Musk', href: '/products?category=body-care&sub=musk' },
      { nameAr: 'ملمع الجسم', nameEn: 'Body Shimmer', href: '/products?category=body-care&sub=shimmer' },
      { nameAr: 'مقشر الجسم', nameEn: 'Body Scrub', href: '/products?category=body-care&sub=scrub' },
      { nameAr: 'شاور جل', nameEn: 'Shower Gel', href: '/products?category=body-care&sub=shower-gel' },
      { nameAr: 'مزيل العرق', nameEn: 'Deodorant', href: '/products?category=body-care&sub=deodorant' },
      { nameAr: 'المنطقة الحساسة', nameEn: 'Intimate Care', href: '/products?category=body-care&sub=intimate' },
      { nameAr: 'العناية باليد', nameEn: 'Hand Care', href: '/products?category=body-care&sub=hand' },
      { nameAr: 'العناية بالقدم والركبة', nameEn: 'Foot & Knee Care', href: '/products?category=body-care&sub=foot' },
      { nameAr: 'أدوات العناية بالجسم', nameEn: 'Body Care Tools', href: '/products?category=body-care&sub=tools' },
    ],
  },
  {
    id: 'hair-care',
    nameAr: 'العناية بالشعر',
    nameEn: 'Hair Care',
    icon: '💇',
    href: '/products?category=hair-care',
    subcategories: [
      { nameAr: 'شامبو وبلسم', nameEn: 'Shampoo & Conditioner', href: '/products?category=hair-care&sub=shampoo' },
      { nameAr: 'ليف إن', nameEn: 'Leave-in', href: '/products?category=hair-care&sub=leave-in' },
      { nameAr: 'جراي شامبو', nameEn: 'Gray Shampoo', href: '/products?category=hair-care&sub=gray-shampoo' },
      { nameAr: 'عطور الشعر', nameEn: 'Hair Perfume', href: '/products?category=hair-care&sub=perfume' },
      { nameAr: 'زيوت وعلاج الشعر', nameEn: 'Hair Oils & Treatment', href: '/products?category=hair-care&sub=oils' },
      { nameAr: 'سيروم الشعر', nameEn: 'Hair Serum', href: '/products?category=hair-care&sub=serum' },
      { nameAr: 'كريم الشعر', nameEn: 'Hair Cream', href: '/products?category=hair-care&sub=cream' },
      { nameAr: 'ماسك الشعر', nameEn: 'Hair Mask', href: '/products?category=hair-care&sub=mask' },
      { nameAr: 'صبغات الشعر', nameEn: 'Hair Dye', href: '/products?category=hair-care&sub=dye' },
      { nameAr: 'مقويات الشعر والبشرة', nameEn: 'Hair & Skin Strengtheners', href: '/products?category=hair-care&sub=strengtheners' },
      { nameAr: 'مجفف ومصفف الشعر', nameEn: 'Hair Dryer & Styler', href: '/products?category=hair-care&sub=styling-tools' },
      { nameAr: 'أدوات العناية بالشعر', nameEn: 'Hair Care Tools', href: '/products?category=hair-care&sub=tools' },
    ],
  },
  {
    id: 'perfumes',
    nameAr: 'العطور',
    nameEn: 'Perfumes',
    icon: '🌸',
    href: '/products?category=perfumes',
    subcategories: [
      { nameAr: 'عطور نسائية', nameEn: "Women's Perfumes", href: '/products?category=perfumes&sub=women' },
      { nameAr: 'عطور رجالية', nameEn: "Men's Perfumes", href: '/products?category=perfumes&sub=men' },
      { nameAr: 'عطور مشتركة', nameEn: 'Unisex Perfumes', href: '/products?category=perfumes&sub=unisex' },
      { nameAr: 'عطور مصغرة', nameEn: 'Mini Perfumes', href: '/products?category=perfumes&sub=mini' },
      { nameAr: 'مجموعات العطور', nameEn: 'Perfume Sets', href: '/products?category=perfumes&sub=sets' },
    ],
  },
  {
    id: 'mens-care',
    nameAr: 'العناية بالرجال',
    nameEn: "Men's Care",
    icon: '👔',
    href: '/products?category=mens-care',
    subcategories: [
      { nameAr: 'العناية بالبشرة', nameEn: 'Skincare', href: '/products?category=mens-care&sub=skincare' },
      { nameAr: 'العناية بالشعر', nameEn: 'Hair Care', href: '/products?category=mens-care&sub=hair' },
      { nameAr: 'العناية باللحية', nameEn: 'Beard Care', href: '/products?category=mens-care&sub=beard' },
      { nameAr: 'مزيل العرق', nameEn: 'Deodorant', href: '/products?category=mens-care&sub=deodorant' },
      { nameAr: 'عطور رجالية', nameEn: "Men's Perfumes", href: '/products?category=mens-care&sub=perfumes' },
    ],
  },
]

export type Category = typeof categories[0]
export type Subcategory = Category['subcategories'][0]
